# PyTorch Basics - Getting Started

This notebook covers the fundamental concepts of PyTorch:
- Tensors and operations
- Automatic differentiation
- Basic neural network construction
- Training loops


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")


PyTorch version: 2.5.1+cu121
CUDA available: True
CUDA device: NVIDIA GeForce GTX 1650


## 1. Working with Tensors
**What is a Tensor?**

By Google's definition:
- It is a multi-dimensional array of numbers that generalizes scalars, vectors, and matrices to higher dimensions. In machine learning and AI, tensors are the fundamental data structure used to represent inputs, outputs, and model parameters (similar to NumPy's ndarrays, but with the ability to run on hardware accelerators like GPUs). More broadly, a tensor is a mathematical object with a specific transformation property under a change of coordinates, giving it a geometric meaning. 

Types of tensors:
- Rank 0 Tensor -> a Scalar, a single number
- Rank 1 Tensor -> a Vector, one-dimensional array of numbers
- Rank 2 Tensor -> a Matrix, a 2 dimensional grid of numbers
- Rank 3 Tensor -> a Three-dimensional grid of numbers
- Rank 4 and nove -> Multi-dimensional arrays with more than 3 dimensions


<img src="nn_tensor_example.png">




Before we start, below is an example of a PyTorch workflow:
<img src="pytorch_workflow.png">




In [2]:
#Introduction and Creating tensors
#Intro to Scalars
scalar = torch.tensor(7)
scalar

tensor(7)

torch.tensor is the most common variable that is used to create almost all the pytorch tensors.

Official documentation: 

https://docs.pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [4]:
#Tensors can be directly created from data
data = [1,2], [3,4]
#convert the data into tensors
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
#create tensors from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
#Let's create a tensor from a tensor
x_ones = torch.ones_like(x_data) #this retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) #this overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3454, 0.3503],
        [0.1050, 0.7709]]) 



In [9]:
#Let's create a tensor with random or constant values
#shape is a tuple of tensor dimensions
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")


Random Tensor: 
 tensor([[0.1981, 0.7919, 0.9392],
        [0.0187, 0.6356, 0.2956]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 2. Tensor Attributes
Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 3. Tensor Operations
Over 100 tensor operations, including transposing, indexing, slicing, math operations, linear algebra, random sampling, all of them can be seen here:

https://docs.pytorch.org/docs/stable/torch.html

Let's try out some of the operations from the Numpy API



In [11]:
#standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [12]:
#For joining tensors, you can use torch.cat() to concatenate a sequence of tensors along a given dimension
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [13]:
#Here is an example of tensor multiplication
#this computes element-wise product
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)} \n")
#alternative syntax:
print(f"tensor * tensor: \n {tensor * tensor} \n")

tensor.mul(tensor): 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor: 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [14]:
#Let's compute the matrix multiplication between two tensors
print(f"tensor.matmul(tensor.T): \n {tensor.matmul(tensor.T)} \n")
#alternative syntax but this does the same thing lol
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T): 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



In [ ]:
#In place operations
#In place operations are denoted by a _ at the end of the method
#This is a common convention in PyTorch for in place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## 4. Bridge with Numpy
Tensors on CPU and Numpy Arrays can share their memory locations, and changing one will change the other.

In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
#a change in the tensor reflects in the numpy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


Numpy array to tensor, where changes in the NumPy array reflects in the tensor

In [19]:
#changes in the numpy array reflects in the tensor
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## 5. Some more PyTorch Basics

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

For faster calculations, you can specify floating points with less digits (e.g float16 is faster to compute than float32)

In [ ]:
#float 32 tensor, and specify the dtype
#and some extra parameters in the functions
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],  
                               dtype=torch.float32, #specify the datatype
                               device = "cpu", #specify cpu / cuda, device needs to be uniform with tensors
                               requires_grad = False) #whether or not to track gradients with the tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
#let's change the float types
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#float16 and float32 multiplication
#this works even tho they're different values, but the same datatype. 
float_mult_test = float_16_tensor * float_32_tensor
float_mult_test

tensor([ 9., 36., 81.])

In [31]:
#Let's test it with a long tensor and float multiplication
long_tensor = torch.tensor([3, 6, 9],  dtype=torch.long)

long_float_mult_test = long_tensor * float_32_tensor
long_float_mult_test

tensor([ 9., 36., 81.])

Getting information from the Tensors


In [32]:
#standard stuff, here we can use a few functions to find out details
#first let's create a tensor first.
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6676, 0.9881, 0.4988, 0.9401],
        [0.3472, 0.1359, 0.4602, 0.8888],
        [0.7470, 0.8018, 0.9236, 0.1418]])

In [37]:
#now get info from it
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.6676, 0.9881, 0.4988, 0.9401],
        [0.3472, 0.1359, 0.4602, 0.8888],
        [0.7470, 0.8018, 0.9236, 0.1418]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])


In [38]:
#find out which device the tensor on
#by default it is in the CPU
print(f"Device tensoris on: {some_tensor.device}")

Device tensoris on: cpu


Manipulating tensors with tensor operations

In [40]:
#create a tensor 
tensor = torch.tensor([1, 2, 3])
tensor_add = tensor + 109
tensor_add

tensor([110, 111, 112])

In [42]:
#multiply the tensor by 10
tensor_mult = tensor * 10
tensor_mult

tensor([10, 20, 30])

In [43]:
#subtract by 10
tensor_sub10 = tensor - 10
tensor_sub10

tensor([-9, -8, -7])

In [46]:
#try out pytorch built-in functions
#matrix multiplication, most common multiplication for neural networks
#also this performs dot products

#this is an example of element-wise multiplication
print(tensor * tensor)

tensor([1, 4, 9])


In [48]:
#now here is matrix multiplication using dot product (1*1 + 2*2 + 3*3)
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
#here's an example of doing it in a for loop and we compare the time from doing a for loop with the pytorch vectorization
value = 0 
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
